name: action

on:
  workflow_dispatch:
  
jobs:
  wakujob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checking out
      - run: python ./.github/workflows/waku.py && ls
        name: Running Script
        env: 
          wakanda_var: 1
          wakanda_var2: 2
      - name: Using local action
        uses: ./
        
